- name: Allow private package registry access
  id: allow-private-package-registry-access
  run: |
    echo "npmScopes:" > ./.yarnrc.yml
    echo "  ${{ github.event.repository.owner.login }}:" >> ./.yarnrc.yml
    echo "    npmRegistryServer: https://registry.npmjs.org" >> ./.yarnrc.yml
    echo "    npmAlwaysAuth: true" >> ./.yarnrc.yml
    echo "    npmAuthToken: ${{ secrets.NPM_ACCESS_TOKEN }}" >> ./.yarnrc.yml
